name: Publish Buf Module

on:
  push:
    branches: [main]

jobs:
  buf-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Buf
        uses: bufbuild/buf-setup-action@v1
      - name: Debug environment and secrets
        run: |
          echo "=== Repository Information ==="
          echo "Repository: ${{ github.repository }}"
          echo "Repository Owner: ${{ github.repository_owner }}"
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Actor: ${{ github.actor }}"
          echo ""
          echo "=== Testing Variables vs Secrets ==="
          echo "Variable buf_token length: ${#VAR_BUF_TOKEN}"
          echo "Secret buf_token length: ${#SECRET_BUF_TOKEN}"
          echo "Variable buf_token exists: ${{ vars.buf_token != '' }}"
          echo "Secret buf_token exists: ${{ secrets.buf_token != '' }}"
          echo ""
          if [ -n "$VAR_BUF_TOKEN" ]; then
            echo "✓ Using buf_token variable"
            echo "$VAR_BUF_TOKEN" | buf registry login --token-stdin
          elif [ -n "$SECRET_BUF_TOKEN" ]; then
            echo "✓ Using buf_token secret"
            echo "$SECRET_BUF_TOKEN" | buf registry login --token-stdin
          else
            echo "❌ Error: buf_token not found as variable or secret"
            echo "Please check GitHub repository settings under:"
            echo "- Settings > Secrets and variables > Actions > Variables tab"
            echo "- Settings > Secrets and variables > Actions > Secrets tab"
            exit 1
          fi
        env:
          VAR_BUF_TOKEN: ${{ vars.buf_token }}
          SECRET_BUF_TOKEN: ${{ secrets.buf_token }}
      - name: Push to Buf
        run: buf push
