name: Publish Buf Module

on:
  push:
    branches: [main]

jobs:
  buf-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Buf
        uses: bufbuild/buf-setup-action@v1
      - name: Debug secrets
        run: |
          echo "Available environment variables:"
          env | grep -E "(BUF|buf)" || echo "No BUF/buf variables found"
          echo "Lowercase buf_token length: ${#BUF_TOKEN_LOWER}"
          echo "Uppercase BUF_TOKEN length: ${#BUF_TOKEN_UPPER}"
          if [ -n "$BUF_TOKEN_LOWER" ]; then
            echo "Using lowercase buf_token secret"
            echo "$BUF_TOKEN_LOWER" | buf registry login --token-stdin
          elif [ -n "$BUF_TOKEN_UPPER" ]; then
            echo "Using uppercase BUF_TOKEN secret"
            echo "$BUF_TOKEN_UPPER" | buf registry login --token-stdin
          else
            echo "Error: Neither buf_token nor BUF_TOKEN secrets are available"
            exit 1
          fi
        env:
          BUF_TOKEN_LOWER: ${{ secrets.buf_token }}
          BUF_TOKEN_UPPER: ${{ secrets.BUF_TOKEN }}
      - name: Push to Buf
        run: buf push
