name: Publish Buf Module

on:
  push:
    branches: [main]

jobs:
  buf-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Buf
        uses: bufbuild/buf-setup-action@v1
      - name: Login to Buf
        env:
          BUF_TOKEN: ${{ secrets.buf_token }}
        run: |
          if [ -z "$BUF_TOKEN" ]; then
            echo "Error: buf_token secret is not set or is empty"
            exit 1
          fi
          echo "$BUF_TOKEN" | buf registry login --token-stdin
      - name: Push to Buf
        run: buf push
